Edit users
kamilsobik/mms-project-ember pull request #8
Opened 2022-10-09 10:04 UTC by kamilsobik

2022-10-12 05:37 UTC, wozny1989 requested changes
Few things but overall nice work, I see you feel it!!! 🕺

2022-10-12 05:37 UTC, wozny1989 commented on app/application/route.js
> +      userType: 'admin',
❤️

2022-10-12 05:37 UTC, wozny1989 commented on app/components/modal/edit-user/component.js
> +  }
How about to do that as you did above?
```suggestion
  @action
  onPasswordChange({ target: { value }}) {
    this.args.user.password = value;
  }

  @action
  onEmailChange({ target: { value }}) {
    this.args.user.email = value;
  }
```

2022-10-12 05:37 UTC, wozny1989 commented on app/components/modal/edit-user/template.hbs
> +          />
How about to create shared input component in this PR? Which by default will have `type='text'` and `class='form-control'`. Example invoke in this case:
```hbs
<Shared::Input
  @id='editEmailInput'
  @type='e-mail'
  @placeholder={{@user.email}}
  @value={{this.email}}
  @onChange={{this.onEmailChange}}
/>
```

2022-10-12 05:37 UTC, wozny1989 commented on app/components/modal/edit-user/template.hbs
> +            placeholder='{{@user.password}}'
Are not necessary
```suggestion
            placeholder={{@user.password}}
```

2022-10-12 05:37 UTC, wozny1989 commented on app/components/modal/edit-user/template.hbs
> +          <div {{on 'input' (fn this.onUserTypeChange 'userType')}}>
Linter not shout about add `role="button"`? 🤔 https://github.com/ember-template-lint/ember-template-lint/issues/41

2022-10-12 05:37 UTC, wozny1989 commented on app/components/modal/edit-user/template.hbs
> +          @onClick={{this.onSaveChange}}
😍

2022-10-12 05:37 UTC, wozny1989 commented on app/components/navbar/component.js
> +  }
🤔 
```suggestion
  get isUserTypeIsRequestor() {
    return Boolean(
      this.session.currentUser.userType === 'requestor' ||
        this.isUserTypeIsAdmin
    );
  }

  get isUserTypeIsResponder() {
    return Boolean(
      this.session.currentUser.userType === 'responder' ||
        this.isUserTypeIsAdmin
    );
  }
```

2022-10-12 05:37 UTC, wozny1989 commented on app/components/navbar/template.hbs
> +        {{/if}}
How about change naming for better readability?
```suggestion
        {{#if this.isRequestorUserType}}
          <li class='nav-item'>
            <LinkTo class='nav-link' @route='home.open-request'>Open new request</LinkTo>
          </li>
        {{/if}}
        {{#if this.isResponderUserType}}
          <li class='nav-item'>
            <LinkTo class='nav-link' @route='home.close-request'>Close request</LinkTo>
          </li>
        {{/if}}
        {{#if this.isAdminUserType}}
          <li class='nav-item'>
            <LinkTo class='nav-link' @route='home.users'>Users</LinkTo>
          </li>
        {{/if}}
```

2022-10-12 05:37 UTC, wozny1989 commented on app/components/user-table/user-table-row/component.js
> +  @action
Please, add empty line between

2022-10-12 05:37 UTC, wozny1989 commented on app/helpers/class-user-table.js
> +export default helper(classUserTable);
Small tip for this condition case, what do you think about that?:
```suggestion
import { helper } from '@ember/component/helper';

const tableClass = {
  requestor: 'table-success',
  responder: 'table-warning',
  admin: 'table-danger'
}

export function classUserTable([userType]) {
  return tableClass[userType] || 'table-primary';
}

export default helper(classUserTable);
```

2022-10-12 05:37 UTC, wozny1989 commented on app/helpers/class-user-table.js
> +  } else if (userType === 'reqponder') {
typo
```suggestion
  } else if (userType === 'responder') {
```

2022-10-12 05:37 UTC, wozny1989 commented on app/register/template.hbs
> +              class='btn-primary btn-lg button-login'
Maybe it's time to add additional property to your Shared::Button like `@size="lg"` (or "sm") which will inject this extra class?

2022-10-12 13:05 UTC, DawidDamek commented on app/components/modal/edit-user/template.hbs
> +            </select>
Maybe try to rewrite it to powerselect🤔 Wodzu fixed the documentation so it should be doable

2022-10-12 13:05 UTC, DawidDamek commented on app/components/navbar/component.js
> +
Dont you have username in `this.session.currentUser.username`? If you have it there you can remove one import

2022-10-12 13:05 UTC, DawidDamek commented on app/components/shared/button/template.hbs
> +  {{@label}}</button>
👌

2022-10-12 13:05 UTC, DawidDamek commented on app/session/service.js
> +      this.loggedAs.set('userType', user.userType);
🤔 why do you set it there?

2022-10-14 11:08 UTC, wozny1989 requested changes

2022-10-14 11:08 UTC, wozny1989 commented on app/components/providers/open-request/template.hbs
> +      @size='btn-lg'
How about:
```suggestion
      @size='lg'
```

and make getter inside shared component something like and concat to basic class:
```js
get size() {
  const { size } = this.args
  const isCorrectSize = ['sm', 'lg'].includes(size);
  return isCorrectSize ? `btn-${size}` : '';
}
```

2022-10-17 07:08 UTC, wozny1989 requested changes

2022-10-17 07:08 UTC, wozny1989 commented on app/utils/form-data.js
> +export { userType };
It should be more readable, and easier to know that it's a collection:
```suggestion
const userTypes = ['admin', 'responder', 'requestor'];

export { userTypes };
```

2022-10-17 07:08 UTC, wozny1989 commented on app/components/modal/edit-user/component.js
> +  userType = userType;
Nice idea with this import! ❤️ One thing:
```suggestion
import { userTypes } from 'mms-ember-project/utils/form-data';

export default class ModalEditUserComponent extends Component {
  userTypes = userTypes;
```

2022-10-17 07:08 UTC, wozny1989 commented on app/components/modal/edit-user/template.hbs
> +          />
Shared component! 💪 
But whats mean `this.email`? I didn't see that property in `component.js`. If you want to display original user email record in `placeholder`, consider to make something like a 'snapshot' this property in constructor and create getter for `this.email`:
```js
constructor() {
  super(...arguments);
  this.originalEmail = this.args.user.email;
}

@computed('args.user.email')
get email() {
  const { lang } = this.args.user.changedAttributes();
  return lang?.[1] || '';
}
```

then:
```suggestion
          <Shared::Input
            @type='email'
            @id='editEmailInput'
            @placeholder={{this.originalEmail}}
            @value={{this.email}}
            @onChange={{this.onEmailChange}}
          />
```

2022-10-17 07:08 UTC, wozny1989 commented on app/components/modal/edit-user/template.hbs
> +          />
same here ☝️

2022-10-17 07:08 UTC, wozny1989 commented on app/register/template.hbs
> +            />
How about create another property, hmm like `variant`?
```suggestion
            <Shared::Button
              class='button-login'
              @variant='primary'
              @size='lg'
              @label='Register new user'
              @type='subtmit'
            />
```

2022-10-17 07:08 UTC, wozny1989 commented on app/helpers/class-user-table.js
> +export default helper(classUserTable);
💪 
+ empty lines 🙏 
```suggestion
import { helper } from '@ember/component/helper';
const tableClass = {
  requestor: 'table-success',
  responder: 'table-warning',
  admin: 'table-danger',
};

export function classUserTable([userType]) {
  return tableClass[userType] || 'table-primary';
}

export default helper(classUserTable);
```

2022-10-17 07:08 UTC, wozny1989 commented on app/helpers/class-table.js
> +};
Keys with dots and white space look weird... Consider to change structure:
```suggestion
const tableClasses = [
  { value: '1.0 tpm', class: 'table-success' },
  { value: '2.0 fault', class: 'table-warning' },
  { value: '3.0 breakdown', class: 'table-danger' }
];
```

2022-10-17 07:08 UTC, wozny1989 commented on app/helpers/class-table.js
> +  return tableClass[typeRequest] || 'table-primary';
then:
```suggestion
  return tableClass.find(({ value }) => value ===  typeRequest).class || 'table-primary';
```

2022-10-17 07:08 UTC, wozny1989 commented on app/components/shared/input/template.hbs
> +/>
Add `...attributes` then you can remove Ember `@class` attribute, then you can pass natively `class` prop, then will be concat other classes to this element (similar like you have in shared/button):
```suggestion
<input
  type={{this.chceckInputType}}
  class='form-control {{this.size}}'
  id={{@id}}
  placeholder='{{@placeholder}}'
  value={{@vale}}
  {{on 'input' @onChange}}
  ...attributes
/>
```

2022-10-17 07:10 UTC, wozny1989 commented
@kamilsobik Additional thing, consider to make second input `password` type as well:
![image](https://user-images.githubusercontent.com/36460224/196111376-5e2d2f5f-fa44-420a-b662-20e5c940e782.png)

2022-11-05 11:09 UTC, wozny1989 requested changes

2022-11-05 11:09 UTC, wozny1989 commented on app/components/modal/edit-user/component.js
> +  changeset = Changeset(this.args.user);
it's working but it's not perfect way - consider ot move this to `contructor` like in this example https://github.com/poteto/ember-changeset#types then will be perfect ❤️

2022-11-05 11:09 UTC, wozny1989 commented on app/components/modal/show-request/template.hbs
> +            @onChange={{this.onDowntimeChange}}
💪

2022-11-05 11:09 UTC, wozny1989 commented on app/components/shared/power-select/template.hbs
> +</PowerSelect>
Almost done! 😄 But what's happen if you'll have other object structure and for proper display you have to use nested key, like:
```hbs
<PowerSelect
  @triggerClass='form-control'
  @selected={{@selected}}
  @options={{@options}}
  @onChange={{@onChange}}
  @placeholder={{@placeholder}}
  as |value|
>
  {{value.name}}
</PowerSelect>
```

I suggest to change:
```suggestion
<PowerSelect
  @triggerClass='form-control'
  @selected={{@selected}}
  @options={{@options}}
  @onChange={{@onChange}}
  @placeholder={{@placeholder}}
  as |value|
>
  {{yield value}}
</PowerSelect>
```

Then using of this component should be always via block type:
```hbs
<Shared::PowerSelect
  @selected={{this.record.machine}}
  @options={{this.machines}}
  @onChange={{fn this.onSelectionChange 'machine'}}
  @placeholder={{'Select machine'}}
  as |value|
>
  {{value}}
</Shared::PowerSelect>
```

or if we have nested structure:
```hbs
<Shared::PowerSelect
  @selected={{this.record.machine}}
  @options={{this.machines}}
  @onChange={{fn this.onSelectionChange 'machine'}}
  @placeholder={{'Select machine'}}
  as |value|
>
  {{value.name}}
</Shared::PowerSelect>
```

2022-11-05 11:09 UTC, wozny1989 commented on app/components/user-table/user-table-row/template.hbs
> +  <Modal::EditUser @onClose={{this.onHideUserModal}} @user={{@user}} />
🔄 
```suggestion
  <Modal::EditUser @user={{@user}} @onClose={{this.onHideUserModal}}/>
```

2022-11-05 11:09 UTC, wozny1989 commented on app/components/providers/open-request/template.hbs
> +      />
https://gist.github.com/wozny1989/30c4c3e2e6a86d773366de933997edbe#file-example_template_refactoring-hbs-L166-L183
```suggestion
      <Shared::PowerSelect
        @placeholder={{'Select request type'}}
        @selected={{this.record.type}}
        @options={{this.requestTypes}}
        @onChange={{fn this.onTypeSelectionChange 'type'}}
      />
```

2022-11-05 11:09 UTC, wozny1989 commented on app/components/providers/open-request/template.hbs
> +      />
same here ⬆️

2022-11-05 11:09 UTC, wozny1989 commented on app/components/shared/button/component.js
> +
🚀

2022-11-05 11:09 UTC, wozny1989 commented on app/components/shared/button/template.hbs
> +  class='btn {{this.size}} {{this.variant}}'
How about create another getter like `buttonClasses`?
```js
get buttonClasses() {
  const classes = ['btn'];
  const { size, variant } = this;
  
  if (size) {
    classes.push(size);
  }

  if (variant) {
    classes.push(variant);
  }

  return classes.join(' ');
}
```

```suggestion
  class={{this.buttonClasses}}
```

2022-11-05 11:09 UTC, wozny1989 commented on app/components/shared/input/template.hbs
> +  class='form-control {{this.size}}'
consider to create similar class as I suggested in `shared/button`

2022-11-05 11:09 UTC, wozny1989 commented on app/components/shared/input/template.hbs
> +  value={{@vale}}
```suggestion
  value={{@value}}
```

2022-11-05 11:09 UTC, wozny1989 commented on app/components/shared/input/template.hbs
> +  {{on 'input' @onChange}}
How about create action inside this component, and pass more comfortable `value` attribute, instead every time taking `event.target.value`. 
Example:
```suggestion
  {{on 'input' this.onChange}}
```

```js
// shared/input/component.js
@action
onChange(event) {
  const { value } = event.target;
  this.args.onChange?.(value, event);
}
```

Then when you'll using this shared component you'll have lovely parameters:
```hbs
<Shared::Input 
  @value={{this.value}}
  @onChange={{this.onChange}}
/>
```

```js
@action
onChange(value, /* event */) {
  this.value = value; // If you want to use event, you have it in second argument 🚀
}
```

2022-11-16 05:46 UTC, wozny1989 commented on app/components/shared/power-select/template.hbs
> +  {{yield value}}
❤️

2022-11-26 15:59 UTC, wozny1989 approved these changes
Nice, I really like it!

2022-11-26 15:59 UTC, merged